# Site settings
title: Back where I belong
header-img: img/home-bg.png
email: trevinla@gmail.com
copyright_name: TrevorSeitz
description: > # this means to ignore newlines until "baseurl:"
  After what feels like a couple of lifetimes, I'm back to coding
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  TrevorSeitz
learn_profile: TrevorSeitz
email_username: trevinla@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
